### ISSUE TITLE
AttributeError: 'DataToFit' object has no attribute 'media_priors_scaled'

### ISSUE THREAD

**Issue by charlesshawmsix** [paramark-inc/mmm#1]
https://github.com/paramark-inc/mmm/blame/4993a04575d4ca2ed445e0974a4c6a832119410c/examples/jupyter/1-validate.ipynb#L129

----> cost_data=data_to_fit.media_priors_scaled,

AttributeError: 'DataToFit' object has no attribute 'media_priors_scaled'

Should the 'media_priors_scaled' be **'media_cost_priors_scaled'**?

Or did you mean ' media_costs_scaled' instead?

**Comment by pete-paramark** [comment]
Sorry about that.  You're right - fixed in c1c2ee9a53822994637194915e39f61fefaef08c.  Thanks for reporting!
