### ISSUE TITLE
TypeError: plot_bars_media_metrics() got an unexpected keyword argument 'bar_height'

### ISSUE THREAD

**Issue by charlesshawmsix** [paramark-inc/mmm#2]
I see the need for the 'bar_height' update as without it all those plots, regardless of whether they are mean or median, would look the same. 

https://github.com/paramark-inc/mmm/blob/c1c2ee9a53822994637194915e39f61fefaef08c/mmm/describe/describe.py#L481

TypeError: plot_bars_media_metrics() got an unexpected keyword argument 'bar_height'

The original LMMM `plot.py` function definition does not include a bar_height (or bar_height_mode) argument, see https://github.com/google/lightweight_mmm/blob/8ac08a189df55f0e17845a05e3f6dbeb3b13fe20/lightweight_mmm/plot.py#L830

Maybe something along these lines might work: 

1) Revise the 'plot_bars_media_metrics' function 

In this revised version of the function:

- I added the bar_height_mode parameter to allow the user to specify whether to use the mean or median for calculating the bar heights.
- I replaced the use of seaborn's barplot with matplotlib's ax.bar for direct control over the bars, including setting the heights and error bars manually. This change provides flexibility in specifying the error bars according to the selected central tendency measure.
- The error bars are calculated based on the quantiles specified by the interval_mid_range parameter.

```
def plot_bars_media_metrics(
    metric: jnp.ndarray,
    metric_name: str = "metric",
    channel_names: Optional[Tuple[Any]] = None,
    interval_mid_range: float = .9,
    bar_height_mode: str = "mean") -> matplotlib.figure.Figure:
  """Plots a barchart of estimated media effects with their percentile interval.

  The lower and upper percentile need to be between 0-1. Allows specifying whether
  to use mean or median for bar heights.

  Args:
    metric: Estimated media metric as returned by lightweight_mmm.get_posterior_metrics().
            Can be either contribution percentage or ROI.
    metric_name: Name of the media metric, e.g., contribution percentage or ROI.
    channel_names: Names of media channels to be added to the plot.
    interval_mid_range: Mid-range interval to take for plotting. E.g., .9 will use
                        .05 and .95 as the lower and upper quantiles. Must be a float number.
    bar_height_mode: Specifies the central tendency measure to use for bar heights ("mean" or "median").

  Returns:
    Barplot of estimated media effects with defined percentile-bars.
  """
  if channel_names is None:
    channel_names = np.arange(metric.shape[1])
  upper_quantile = 1 - (1 - interval_mid_range) / 2
  lower_quantile = (1 - interval_mid_range) / 2

  # Calculate central tendency
  if bar_height_mode == "mean":
    central_tendency = metric.mean(axis=0)
  elif bar_height_mode == "median":
    central_tendency = np.median(metric, axis=0)
  else:
    raise ValueError("bar_height_mode must be 'mean' or 'median'")

  quantile_bounds = np.quantile(metric, q=[lower_quantile, upper_quantile], axis=0)
  error_bars = np.abs(quantile_bounds - central_tendency)

  fig, ax = plt.subplots(1, 1)
  ax.bar(np.arange(len(central_tendency)), central_tendency, yerr=error_bars, capsize=5)
  ax.set_xticks(np.arange(len(channel_names)))
  ax.set_xticklabels(channel_names, rotation=60, ha="right", rotation_mode="anchor")
  fig.suptitle(f"Estimated media channel {metric_name}. \n Error bars show "
               f"{np.round(lower_quantile, 2)} - {np.round(upper_quantile, 2)} "
               f"credibility interval. Mode: {bar_height_mode.capitalize()}.")

  plt.close(fig)  # If you're running this in a script you might want to remove this line to see the plot
  return fig
```

2) then you can use this new argument as follows

```
fig = plot_bars_media_metrics(
        metric=media_effect_hat,
        metric_name="contribution percentage",
        channel_names=data_to_fit.media_names,
        bar_height_mode="mean",
    )
```

**Comment by pete-paramark** [comment]
Hi, thanks for filing this issue.  I expect your python references may not be resolving as expected.

This repo includes https://github.com/paramark-inc/lightweight_mmm as a submodule -- Paramark's fork of Lightweight MMM which includes bug fixes and a few small enhancements.  If your python path includes mmm/impl/lightweight_mmm, it should resolve this type error.

For example, you can add "/path/to/mmm/impl/lightweight_mmm" to your python path.

**Comment by charlesshawmsix** [comment]
Ah yes, I was using the vanilla Google's lightweightMMM. I now see you have forked it, makes total sense.
